function Data = ImportGPSData(file)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/vaningen/MEGAsync/MSc Sensor Fusion Thesis/Code and Datasets/SHS Code/datasets/3_times_around_the_block/location-gps.txt
%
% Auto-generated by MATLAB on 05-Jul-2020 18:50:28

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [7, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Time", "elapsedtimesensor", "latitude", "longitude", "altitude", "bearing", "accuracy", "speed"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
Data = readtable(file, opts);
Data.Time = (Data.Time(:)-Data.Time(1));
Data.Time = seconds(Data.Time);
Data = table2timetable(Data);
Data = unique(Data);

%% Clear temporary variables
clear opts