function [Data, elapsed] = TSVFile2Timetable(dataset, dataLines)
%IMPORTFILE Import data from a text file
%  HIMU1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  HIMU1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  HIMU1 = importfile("/home/vaningen/MEGAsync/MSc Sensor Fusion Thesis/Datasets/HIMU-2020-03-24_18-58-04.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Mar-2020 09:54:39

%% Input handling

file = dataset.file;
% dataSetProp = dataset.dataSetProp;
file_path = strcat(file.directory, file.name);

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "Type", "x", "y", "z"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Type", "EmptyFieldRule", "auto");

% Import the data
Data = readtable(file_path, opts);

% find elapsed time and transform from milliseconds to seconds
Data.Time(:) = Data.Time(:) - Data.Time(1);
milli2sec = Data.Time(:).*(1/1000);
Data.Time = seconds(milli2sec);
Data = table2timetable(Data);
Data = unique(Data);

%% Clear temporary variables
clear opts

end